services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/app
    ports:
      - '8001:80'
    depends_on:
      - php
  php:
    build:
      context: ./docker/php
      target: ${APP_ENV:-0}
      args:
        USER_ID: ${USER_ID:-0}
    volumes:
      - ./:/app
    depends_on:
      - base-db
  cron-php:
    restart: always
    build:
      context: ./docker/php
      target: cron
      args:
        USER_ID: ${USER_ID:-0}
    volumes:
      - ./project:/app
      - ./project/var/cron_var:/var/log
    depends_on:
      - base-db
  base-db:
    restart: always
    image: postgres:16.1-alpine3.19
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=db_user"
      - "POSTGRES_PASSWORD=db_password"
      - "POSTGRES_DB=db_name"
    ports:
      - "33069:5432"
#  localstack:
#    image: localstack/localstack:3.7
#    container_name: ons-localstack
#    ports:
#      - '4566:4566'
#      - '4510-4559:4510-4559'
#    environment:
#      DEBUG: '1'
#      SERVICES: 'sqs,s3'
#      AWS_DEFAULT_REGION: '${AWS_REGION:-us-east-1}'
#      AWS_REGION: '${AWS_REGION:-us-east-1}'
#      LOCALSTACK_HOST: '${LOCALSTACK_URL:-host.docker.internal}'
#      SKIP_SSL_CERT_DOWNLOAD: '1'
#      PERSISTENCE: '1'
#    volumes:
#      - ${BASE_DIR:-./docker}/localstack:/var/lib/localstack
#      - /var/run/docker.sock:/var/run/docker.sock
#    env_file:
#      - ./.env.local
#    networks:
#      default:
#        aliases:
#          - ${LOCALSTACK_URL:-localstack}
#          - sqs.us-east-1.${LOCALSTACK_URL:-localstack}
#          - sqs.us-east-1.host.docker.internal

#  maildev:
#    image: axllent/mailpit:v1.20
#    container_name: ons-maildev
#    ports: !override
#      - "1025:1025"
#      - "8025:8025"
#    environment:
#      MP_SMTP_AUTH_ACCEPT_ANY: '1'
#      MP_SMTP_AUTH_ALLOW_INSECURE: '1'

volumes:
  postgres_data:
